-- create users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    trusted_user_id BIGINT,
    
    CONSTRAINT fk_users_trusted_user FOREIGN KEY (trusted_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_users_trusted_user ON users(trusted_user_id ASC);

-- create devices
CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address VARCHAR(17) UNIQUE NOT NULL,
    name VARCHAR(100),
    user_id BIGINT,
    is_activated BOOLEAN DEFAULT FALSE NOT NULL,
    
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- create alerts 
CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_alerts_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);