spring:
  application:
    name: AudioViolenceDetectionApplication
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT_EXTERNAL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT_EXTERNAL:6379}

  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT_EXTERNAL:19092}
    consumer:
      group-id: audio-violence-group
      auto-offset-reset: earliest

server:
  port: ${APP_PORT}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:86400}

  mqtt:
    broker-url: tcp://localhost:${MQTT_PORT_EXTERNAL:1883}
    client-id: spring-boot-backend-service
    topic: devices/alerts